config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'static_pages#home'
#  mount Sidekiq::Web, at: '/sidekiq'
#  mount Resque::Server, :at => "/resque"
  mount Shrine.presign_endpoint(:cache) => "/data_files/upload/cache/presign"
  mount Shrine.presign_endpoint(:cache) => "/photos/upload/cache/presign"
  
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  
  get     'settings'         => 'static_pages#settings'
  get     'team'         => 'static_pages#team'
  get     'testimonials'         => 'static_pages#testimonials'
  get     'terms'         => 'static_pages#terms'
  get     'privacy'         => 'static_pages#privacy'
  get     'login'             => 'sessions#new'
  post    'login'             => 'sessions#create'
  delete  'logout'            => 'sessions#destroy'
  
  resources :journies do
    collection do 
      get :start
      get :living
      post :update_living
      get :medical
      post :update_medical
      get :budget
      post :update_budget
      get :veteran
      patch :update_veteran
      get :activities
      post :update_activities
      get :prospect_priorities
      post :update_prospect_priorities
      get :lead_priorities
      post :update_lead_priorities
      get :prospect_name
      patch :update_prospect_name
      get :lead_name
      get :update_lead_name
      patch :update_lead_name
      get :age
      post :update_age
      get :phone
      patch :update_phone
      get :validate_code
      post :check_code
      get :email
      patch :update_email
      get :rep
      get :location_search
      get :distance_search
      post :update_prospective_communities
    end
  end
  
  resources :users do
    get :password
    post :resend_activation_email
    patch :update_password
    
    collection do
      put :update_multiple
    end
  end
  
  resources :companies do
    resources :data_files
    get :new_note
    post :save_note
    collection do
      get :autocomplete
    end 
  end
  
  resources :pharmacies do
    get :new_note
    post :save_note
    collection do
    end
  end
  
  resources :contacts do
    resources :data_files
    get :distance_search
    get :community_search
    get :new_note
    get :new_result
    get :new_respite
    get :edit_result
    get :edit_finance
    get :decision_makers
    get :send_claim_email
    post :update_prospective_communities
    post :destroy_prospective_communities
    post :save_note
    post :save_result
    patch :save_result
    post :save_respite
    patch :save_finance
    patch :add_family
    put :update_decision_makers
    collection do
      get :autocomplete_resident
      get :autocomplete_family
      get :autocomplete_business
      get :autocomplete_clinician
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end

  resources :community_search, only: [:index, :show] do
    collection do
      post :index
      get :add_to_interest
      get :get_contact
      post :submit_contact
    end
  end

  resources :communities do
    resources :data_files
    resources :photos
    get :new_note
    post :save_note
    get :autocomplete_pharmacies
    collection do
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end
  
  resources :activities do
    collection do
      put :update_multiple
    end
  end
  resources :dinings do
    collection do
      put :update_multiple
    end
  end
  resources :positions do
    collection do
      put :update_multiple
    end
  end
  resources :features do
    collection do
      put :update_multiple
    end
  end
  resources :license_types do
    collection do
      put :update_multiple
    end
  end
  resources :result_types do
    collection do
      put :update_multiple
    end
  end
  resources :placement_statuses do
    collection do
      put :update_multiple
    end
  end
  resources :medicaid_providers do
    collection do
      put :update_multiple
    end
  end
  resources :zip_codes do
    collection do
      get :autocomplete
    end 
  end
  
  resources :cities do
    collection do
      get :autocomplete
      get :autocomplete_name
    end
  end
  
  resources :users,               except: [:destroy]
  resources :account_activations, only: [:edit]
  resources :validations, only: [:edit]
  resources :notes,               only: [:destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :photos, only: [:update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :admin_user, only: [:settings]
  
  def home
    if session[:city].present?
      @city = session[:city]
    else
      results = Geocoder.search(remote_ip())
      @city = results.first.city + ', ' + results.first.region_code
    end

    if logged_in?
      redirect_to current_user
    end
  end

  def privacy
  end

  def terms
  end

  def team
  end

  def testimonials
  end

  def settings
    @activities = Activity.all
    @activity = Activity.new
    @dinings = Dining.all
    @dining = Dining.new
    @features = Feature.all
    @feature = Feature.new
    @licenses = LicenseType.all
    @license = LicenseType.new
    @results = ResultType.all
    @result = ResultType.new
    @providers = MedicaidProvider.all
    @provider = MedicaidProvider.new
    @positions = Position.all
    @position = Position.new
    @statuses = PlacementStatus.all
    @status = PlacementStatus.new
    @users = User.all
    @new_user = User.new
  end
  
  private
    def admin_user
      if logged_in?
        redirect_to current_user, flash: { danger: "Administrator permission required" } unless current_user.admin?
      else
        flash[:danger] = "Authorization failure"
        redirect_to root_url
      end
    end
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

  <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  <div class="jumbotron bg" id="search">
    <div class="row" style="padding-top: 30px">
      <div class="text-center">
        <h1 style="color: white;text-shadow: 2px 2px black;">Find your Home</h1>
        <%= form_tag(community_search_index_path) do %>
          <div class="col-md-4 col-md-offset-4">
            <div class="input-group" style="margin: 10px">
              <%= text_field_tag :city, nil, { placeholder: "Search #{@city} or enter city", class: 'main-input-box form-control text-center', id: 'city' } %>
              <div class="input-group-btn">
                <%= button_tag type: 'submit', class: "btn btn-primary", style: 'margin-top: 10px; font-size: 20px' do %>
                  <%= fa_icon('search') %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
    <br>
    <!-- Page Content -->
    <br>
    <div class="container info-box">
        <div class="row">
          <div class="col-lg-6 mb-6">
            <script src="https://fast.wistia.com/embed/medias/5weehvh9cp.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_5weehvh9cp videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/5weehvh9cp/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>
          </div>
          <div class="col-lg-6 mb-6">
            <div class="card h-100">
              <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Making the Right Choice</h4>
              <div class="card-body">
                <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
                  When it comes to an aging loved one, we understand your concerns, and have spent years developing a resource to help.  Your loved one’s care needs professional and unbiased expertise to help you make “The Right Choice”.  To eliminate the guesswork we have personally researched, evaluated, and interviewed clients, caregivers, community professionals, and their management to ensure that we provide you the needed information on the BEST care homes your local community has to offer.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>

    <section class="parallax" style='background-image: url("https://cdn.sotercares.com/images/soter-workshop.jpg");'>
      <div style="background-color: rgba(0,0,0,0.5); padding-top: 20px; padding-bottom: 20px;">
        <div class="container">
          <blockquote class="blockquote" style="color: white;">
            <p class="mb-0" style="padding-top: 15px; color: white;">
              <em>"I only wish there were more than five stars I could award Geri 
              because she is a truly gifted family advocate."</em>
            </p>
            <footer class="blockquote-footer" style="color: white; text-align: right">Susan<br><cite title="Source Title">Melbourne, FL</cite></footer>
          </blockquote>
        </div>
      </div>
    </section>
    <br>
    
    <div class="container info-box">
        <div class="row">
          <div class="col-lg-4 mb-4">
            <img class="img-fluid rounded hidden-sm hidden-xs" src="https://cdn.sotercares.com/images/IMG_1606.jpg" alt="">
          </div>
          <div class="col-lg-8 mb-8">
            <div class="card h-100">
              <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Getting it Right the First Time</h4>
              <div class="card-body">
                <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
                  At Soter we understand that caring for relatives can be rewarding but also stressful, time consuming and emotionally exhausting.  It is difficult for families to juggle work, children and other obligations and still find time to properly care for an aging parent as well as themselves.  This website is designed to help you do the research you need, get the support you need, and get you back to being a son, daughter, or friend again.
                  <br><br>
                  <strong>OUR PROCESS:</strong>
                  <ol style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
                    <li>Go through the initial search online.</li>
                    <li>Your Family Advocate will travel to you for a Care Consultation. They will simply meet with you regarding the initial survey, assessing your personal, financial, and clinical needs. This also helps us determine the timing of your need… Is this an emergency or are you a family being proactive with your research?</li>
                    <li>The results of the Care Consultation are then compared with local healthcare solutions or facilities that have an excellent record and meet our high standards.</li>
                    <li>Your Family Advocate will then reach out and discuss our findings with you and answer any questions you have.  We will then call to set up any appointments and accompany you on personalized tours of the various care options until a solution is found… At whatever your pace.  We are simply here to advocate for you, your family, and be on your side.</li>
                  </ol>
                  <div style="text-align: center">
                    <strong>THIS SERVICE IS AVAILABLE TO YOU AT NO COST</strong>
                  </div>
                </p>
              </div>
            </div>
          </div>
        </div>
      <br>
    <br>
        <div class="row">
          <div class="col-lg-6 mb-8">
            <div class="card h-100">
              <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Is it Time to Look for Senior Housing?</h4>
              <div class="card-body"  style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
                <p class="card-text">
                  Most people don’t want to move from their home into Assisted Living. However, in some cases it is the best option to keep elderly or aging parents safe and healthy. There are many signs to watch for to determine if it’s time for a loved one to move.
                </p>
              
                <ul class="card-text">
                  <li>Unable to keep up with maintaining the house</li>
                  <li>Driving Skills have gotten worse</li>
                  <li>Loss of balance, movement, coordination</li>
                  <li>Falls, possibly trying to cover up bruises.</li>
                  <li>Increased medication mistakes</li>
                  <li>Stacks of papers and unpaid bills lying around</li>
                  <li>Memory problems / Becoming forgetful / Repeating themselves</li>
                  <li>Personal hygiene is becoming an issue</li>
                  <li>Signs of depression</li>
                </ul>

                <p class="card-text">
 
                  <strong>NETWORK OF PROFESSIONALS:</strong>
                  <br>
                  Soter regularly communicates and networks with a complete team of professionals that we can refer you and your family to. This can make many of the challenges families face a little easier. From Home Health Care to Elder Law Attorneys, Professional Guardians to Handymen, we can refer you to the right people at the right time!
                </p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 mb-4">
            <script src="https://fast.wistia.com/embed/medias/dh7wxgkncg.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_dh7wxgkncg videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/dh7wxgkncg/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" aria-hidden="true" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>
          </div>
        </div>
      <br>
      <br>
        <div class="row">
          <div class="col-lg-6 mb-6">
            <br>
            <img class="img-fluid rounded" src="https://cdn.sotercares.com/images/Team-2.jpg" alt="">
          </div>
          <div class="col-lg-6 mb-6">
            <div class="card h-100">
              <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Who We Are</h4>
              <div class="card-body"  style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
                <p class="card-text">
                    The Team at Soter Senior Living and Family Advocates includes people of different backgrounds within the Healthcare industry combining over 80 years of experience.  This was done with purpose and intent as it is our belief that this combined expertise provides the very best solutions for seniors and their families no matter the situation.
                   <br><br>
                    Soter Senior Living and Family Advocates provides four types of services:
                      <ul>
                        <li>In-Home Senior Care advice and local community providers</li>
                        <li>Unbiased Senior Living information and tour assistance locally or out of area</li>
                        <li>Home monitoring and Medication reminder services</li>
                        <li>Financial care coordination (Long Term Care Insurance, Veteran’s Pension Benefits, & Bridge Loan providers)</li>
                      </ul>
                  <div style="text-align: center">
                    <strong>WE ARE THERE EVERY STEP OF THE WAY!</strong>
                  </div>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
          <br>
      <section class="parallax" style='background-image: url("https://cdn.sotercares.com/images/Victoria+Landing+515+0830.JPG");'>
        <div class="container">
          <div style="text-align: center; padding-top: 90px">
            <h2 style="color: white; text-shadow: 2px 2px #000000">World Class Communities</h2>
            <%= link_to "Start your Search", '#search', class: "btn btn-danger btn-lg" %>
          </div>
        </div>
      </div>
    </section>
    
    <br>

    <hr>
    <div class="container info-box">
        <div class="row">
            <div class="col-md-12" style="text-align: center">
              <h3>Contact Us:</h3>
              <br>
              Office:  321-419-0041<br>
              Toll Free:  888-976-8371<br>
              Fax:  321-312-3751<br>
              52 NW Carolina Street, West Melbourne, FL 32904<br>
            </div>
        </div>
      </div>
    </div>
    <br>

<script>
    $("#city").autocomplete({
        source: "/cities/autocomplete_name",
        minLength: 3,
        select: function(event, ui) {
            event.preventDefault();
            $("#city").val(ui.item.label);
        },
        focus: function(event, ui) {
            event.preventDefault();
            $("#city").val(ui.item.label);
        }
    });
</script>

app/views/static_pages/orig_home.html.erb
<% provide(:title, "Home") %>
<% cache do %>
<div class="row">
  <div class="col-md-4">
    <h3>Welcome to Soter Family Advocates</h3>
    <h4>
      For access, please contact a system administrator
    </h4>
    <%= link_to "Log in", login_path, class: "btn btn-primary" %>
  </div>
  
</div>
<% end %>

app/views/static_pages/settings.html.erb
<% provide(:title, 'Settings') %>
<div class="container">
  <h1>Settings</h1>
  <div id="accordion">
    <h3>License Types</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_license_types_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>License Type</th>
              <th>Clinical Needs</th>
              <th></th>
            </tr>
            <% @licenses.order(name: :desc).each do |license| %>
              <%= fields_for "licenses[]", license do |f| %>
                <tr>
                  <td><%= f.text_field :name, class: 'form-control' %></td>
                  <td><%= f.text_area(:license_list, cols: 20, rows: 3,
                                      placeholder:         "Clinical Needs (separate with commas)",
                                      class:               'form-control',
                                      style:               "overflow-y: scroll") %></td>
                  <td><%= link_to "Delete", license, method: :delete,
                                  data:                      { confirm: "Are you sure you want to delete #{license.name}?" },
                                  class:                     "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Licenses", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_tag update_multiple_license_types_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>License Type</th>
              <th>Clinical Needs</th>
              <th></th>
            </tr>
            <% @licenses.order(name: :desc).each do |license| %>
              <%= fields_for "licenses[]", license do |f| %>
                <tr>
                  <td><%= f.text_field :name, class: 'form-control' %></td>
                  <td><%= f.text_area(:license_list, cols: 20, rows: 3,
                                      placeholder:         "Clinical Needs (separate with commas)",
                                      class:               'form-control',
                                      style:               "overflow-y: scroll") %></td>
                  <td><%= link_to "Delete", license, method: :delete,
                                  data:                      { confirm: "Are you sure you want to delete #{license.name}?" },
                                  class:                     "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Licenses", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@license) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th> New License</th>
            </tr>
            <tr>
              <td><%= f.text_field :name, class: 'form-control',
                                   placeholder:  "New License Type" %></td>
            </tr>
          </table>
          <%= f.submit "Create License", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <h3>Results</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_result_types_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Result</th>
              <th></th>
            </tr>
            <% @results.each do |result| %>
              <%= fields_for "results[]", result do |f| %>
                <tr>
                  <td><%= f.text_field :name, class: 'form-control' %></td>
                  <td><%= link_to "Delete", result, method: :delete,
                                  data:                     { confirm: "Are you sure you want to delete #{result.name}?" },
                                  class:                    "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Results", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@result) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>New Result</th>
            </tr>
            <tr>
              <td><%= f.text_field :name, class: 'form-control',
                                   placeholder:  "New Result" %></td>
            </tr>
          </table>
          <%= f.submit "Create Result", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <h3>Positions</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_positions_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Position</th>
              <th>Clinician</th>
              <th></th>
            </tr>
            <% @positions.each do |position| %>
              <%= fields_for "positions[]", position do |f| %>
                <tr>
                  <td><%= f.text_field :title, class: 'form-control' %></td>
                  <td><%= f.check_box :clinician %></td>
                  <td><%= link_to "Delete", position, method: :delete,
                                  data:                       { confirm: "Are you sure you want to delete #{position.title}?" },
                                  class:                      "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Positions", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@position) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th> New Position</th>
            </tr>
            <tr>
              <td><%= f.text_field :title, class: 'form-control',
                                   placeholder:   "New Position" %></td>
            </tr>
          </table>
          <%= f.submit "Create Position", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <h3>Placement Status</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_placement_statuses_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Status</th>
              <th></th>
            </tr>
            <% @statuses.each do |status| %>
              <%= fields_for "placement_statuses[]", status do |f| %>
                <tr>
                  <td><%= f.text_field :status, class: 'form-control' %></td>
                  <td><%= link_to "Delete", status, method: :delete,
                                  data:                     { confirm: "Are you sure you want to delete #{status.status}?" },
                                  class:                    "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Placement Statuses", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@status) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>New Status</th>
            </tr>
            <tr>
              <td><%= f.text_field :status, class: 'form-control',
                                   placeholder:    "New Placement Status" %></td>
            </tr>
          </table>
          <%= f.submit "Create Placement Status", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <h3>Medicaid Providers</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_medicaid_providers_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Provider</th>
              <th></th>
            </tr>
            <% @providers.each do |provider| %>
              <%= fields_for "medicaid_providers[]", provider do |f| %>
                <tr>
                  <td><%= f.text_field :name, class: 'form-control' %></td>
                  <td><%= link_to "Delete", provider, method: :delete,
                                  data:                       { confirm: "Are you sure you want to delete #{provider.name}?" },
                                  class:                      "btn btn-danger btn-sm", style: "color: white" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Medicaid Providers", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@provider) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>New Provider</th>
            </tr>
            <tr>
              <td><%= f.text_field :name, class: 'form-control',
                                   placeholder:  "New Medicaid Provider" %></td>
            </tr>
          </table>
          <%= f.submit "Create Medicaid Provider", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
    <h3>Employees</h3>
    <div>
      <div class="row">
        <%= form_tag update_multiple_users_path, method: :put do %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Name</th>
              <th>Email</th>
              <th>Profile</th>
              <th>Pic Link</th>
              <th>Admin</th>
              <th>Disable</th>
            </tr>
            <% @users.each do |user| %>
              <%= fields_for "users[]", user do |u| %>
                <tr>
                  <td><%= u.text_field :name, class: 'form-control' %></td>
                  <td><%= u.email_field :email, class: 'form-control' %></td>
                  <td><%= u.text_field :profile, class: 'form-control' %></td>
                  <td><%= u.text_field :pic_link, class: 'form-control' %></td>
                  <td><%= u.check_box :admin %></td>
                  <td><%= u.check_box :disable %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
          <%= submit_tag "Update Users", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
      <br>
      <div class="row">
        <%= form_for(@new_user) do |f| %>
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <th>Name</th>
              <th>Email</th>
              <th>Profile</th>
              <th>Pic Link</th>
              <th>Admin</th>
              <th>Disable</th>
            </tr>
            <tr>
              <td><%= f.text_field :name, class: 'form-control', placeholder: "New employee name" %></td>
              <td><%= f.email_field :email, class: 'form-control', placeholder: "New employee email" %></td>
              <td><%= f.email_field :profile, class: 'form-control', placeholder: "Employee profile..." %></td>
              <td><%= f.email_field :pic_link, class: 'form-control', placeholder: "Picture Link" %></td>
              <td><%= f.check_box :admin %></td>
              <td><%= f.check_box :disable %></td>
            </tr>
          </table>
          <%= f.submit "Create User", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>

  $( "#accordion" ).accordion({ 
    collapsible: true,
    heightStyle: "content"
  });
</script>