config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'static_pages#home'
#  mount Sidekiq::Web, at: '/sidekiq'
#  mount Resque::Server, :at => "/resque"
  mount Shrine.presign_endpoint(:cache) => "/data_files/upload/cache/presign"
  mount Shrine.presign_endpoint(:cache) => "/photos/upload/cache/presign"
  
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  
  get     'settings'         => 'static_pages#settings'
  get     'team'         => 'static_pages#team'
  get     'testimonials'         => 'static_pages#testimonials'
  get     'terms'         => 'static_pages#terms'
  get     'privacy'         => 'static_pages#privacy'
  get     'login'             => 'sessions#new'
  post    'login'             => 'sessions#create'
  delete  'logout'            => 'sessions#destroy'
  
  resources :journies do
    collection do 
      get :start
      get :living
      post :update_living
      get :medical
      post :update_medical
      get :budget
      post :update_budget
      get :veteran
      patch :update_veteran
      get :activities
      post :update_activities
      get :prospect_priorities
      post :update_prospect_priorities
      get :lead_priorities
      post :update_lead_priorities
      get :prospect_name
      patch :update_prospect_name
      get :lead_name
      get :update_lead_name
      patch :update_lead_name
      get :age
      post :update_age
      get :phone
      patch :update_phone
      get :validate_code
      post :check_code
      get :email
      patch :update_email
      get :rep
      get :location_search
      get :distance_search
      post :update_prospective_communities
    end
  end
  
  resources :users do
    get :password
    post :resend_activation_email
    patch :update_password
    
    collection do
      put :update_multiple
    end
  end
  
  resources :companies do
    resources :data_files
    get :new_note
    post :save_note
    collection do
      get :autocomplete
    end 
  end
  
  resources :pharmacies do
    get :new_note
    post :save_note
    collection do
    end
  end
  
  resources :contacts do
    resources :data_files
    get :distance_search
    get :community_search
    get :new_note
    get :new_result
    get :new_respite
    get :edit_result
    get :edit_finance
    get :decision_makers
    get :send_claim_email
    post :update_prospective_communities
    post :destroy_prospective_communities
    post :save_note
    post :save_result
    patch :save_result
    post :save_respite
    patch :save_finance
    patch :add_family
    put :update_decision_makers
    collection do
      get :autocomplete_resident
      get :autocomplete_family
      get :autocomplete_business
      get :autocomplete_clinician
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end

  resources :community_search, only: [:index, :show] do
    collection do
      post :index
      get :add_to_interest
      get :get_contact
      post :submit_contact
    end
  end

  resources :communities do
    resources :data_files
    resources :photos
    get :new_note
    post :save_note
    get :autocomplete_pharmacies
    collection do
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end
  
  resources :activities do
    collection do
      put :update_multiple
    end
  end
  resources :dinings do
    collection do
      put :update_multiple
    end
  end
  resources :positions do
    collection do
      put :update_multiple
    end
  end
  resources :features do
    collection do
      put :update_multiple
    end
  end
  resources :license_types do
    collection do
      put :update_multiple
    end
  end
  resources :result_types do
    collection do
      put :update_multiple
    end
  end
  resources :placement_statuses do
    collection do
      put :update_multiple
    end
  end
  resources :medicaid_providers do
    collection do
      put :update_multiple
    end
  end
  resources :zip_codes do
    collection do
      get :autocomplete
    end 
  end
  
  resources :cities do
    collection do
      get :autocomplete
      get :autocomplete_name
    end
  end
  
  resources :users,               except: [:destroy]
  resources :account_activations, only: [:edit]
  resources :validations, only: [:edit]
  resources :notes,               only: [:destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :photos, only: [:update]
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :communities
  has_many :contacts
  has_many :payments
  has_many :invoices
  
  belongs_to :user
  belongs_to :zip_code
  
  has_many :notes, as: :notable, dependent: :destroy
  has_many :data_files, as: :fileable, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 50 }
  
  attribute :community, :string
  attribute :community_id, :integer
  
  def self.search(search)
    if search
      where('name ilike ?', "%#{search}%")
    else
      nil
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user, only: [:destroy]
  before_action :set_company, only: [:show, :edit, :update, :new_note, :save_note,
                                :destroy]
  
  def destroy
    if @company.invoices.empty? && @company.payments.empty?
      @company.contacts.update_all(company_id: nil)
      @company.communities.update_all(company_id: nil)
      if @company.delete
        redirect_to companies_path, flash: { success: "#{@company.name} successfully deleted." }
      else
        redirect_to companies_path, flash: { danger: "Something went wrong." }
      end
    else
      redirect_to companies_path, flash: { danger: "Unable to delete #{@community.name}. Please delete all invoices, payments, and phramcies and try again." }
    end
  end
  
  def autocomplete
    @companies = Company.search(params[:term])
    @company_hash = []
    @companies.each do |company|
        label = company.name
        if company.zip_code
          label << " - #{company.zip_code.city.name}, #{company.zip_code.city.county.state.two_digit_code}"
        else
          label << " - Unknown Address"
        end
        
        @company_hash << { 
            label: label,
            value: company.id 
        }
    end
    
    render json: @company_hash
  end
  
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_params)
    @company.user = current_user
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @company.update(company_params)
    @data_file = DataFile.new
    if params[:company][:community_id].present?
      @company.communities << Community.find_by_id(params[:company][:community_id])
    end
  end
  
  def show
    @data_file = DataFile.new
  end
  
  def index
    search = params[:search] || nil
    if search
      @companies = Company.search(params[:search]).order(name: :asc).paginate(page: params[:page], :per_page => 50)
    else
      @companies = Company.order(name: :asc).paginate(page: params[:page], :per_page => 50)
    end
  end
  
  def new_note
    @note = Note.new
  end
  
  def save_note
    @note = Note.new(note_params)
    @note.user = current_user
    @company.notes << @note
    @data_file = DataFile.new
    respond_to do |format|
      format.html
      format.js { render 'update.js.erb' }
    end
  end
  
  private
    def company_params
      list_params_allowed = [:company_id,
          :name, :address_1, :address_2, :zip, :zip_code_id, 
          :phone_number, :fax, :community_id, :website]
          
      list_params_allowed << :user_id if current_user.admin?
      params.require(:company).permit(list_params_allowed)
    end
    
    def note_params
      params.require(:note).permit(:content)
    end
    
    def logged_in_user
      redirect_to root_url, flash: { danger: "Authorization failure" } unless logged_in?
    end
  
    def set_company
      @company = Company.find_by_id(params[:id]) || Company.find_by_id(params[:company_id])
    end
    
    def admin_user
      redirect_to root_url, flash: { danger: "Authorization failure" } unless current_user.admin?
    end
end

app/views/companies/_company.html.erb
<h3><%= @company.name %>
<%= link_to "Edit Name", edit_company_path(@company, section: :name),
            {remote: true, data: { toggle: "modal", target: '#modal-window' },  
            class: "btn btn-default btn-xs" } %></h3>


<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      Company Information
      <%= link_to "Update", edit_company_path(@company, section: :info),
          {remote: true, data: { toggle: "modal", target: '#modal-window' },  
          class: "btn btn-default btn-xs pull-right" } %>
    </div>
    <div class="panel-body">
      <table class="table table-condensed ero-table">
        <tr>
          <td style='font-weight: bold'>Name:</td><td><%= @company.name %></td>
        </tr>
        <tr>
          <td style='font-weight: bold'>Website:</td><td><%= link_to @company.website, @company.website if @company.website.present? %></td>
        </tr>
        <tr>
          <td style='font-weight: bold'>Phone:</td><td><%= link_to number_to_phone(@company.phone_number, area_code: true), "tel:#{@company.phone_number}" %></td>
        </tr>
        <tr>
          <td style='font-weight: bold'>Fax:</td><td><%= number_to_phone(@company.fax, area_code: true) %></td>
        </tr>
        <tr>
          <td style='font-weight: bold'>Address:</td>
          <td>
              <% if @company.zip_code %>
                <%= @company.address_1 %><br>
                <% if @company.address_2.present? %>
                  <%= @company.address_2 %><br>
                <% end %>
                <%= @company.zip_code.city.name %> <%= @company.zip_code.city.county.state.two_digit_code %>, <%= @company.zip_code.code %>
              <% end %>
          </td>
        </tr>
      </table>
    </div> 
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      Contacts
    </div>
    <div class="panel-body">
      <table class="table table-condensed ero-table">
        <tr  style='font-weight: bold'>
          <td>Name</td>
          <td>Position</td>
        </tr>
        <% @company.contacts.each do |contact| %>
          <tr>
            <td><%= link_to contact.first_name + " " + contact.last_name, contact %></td>
            <td><%= contact.position.title if contact.position %></td>
          </tr>
        <% end %>
      </table>
    </div> 
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      Communities
      <%= link_to "Add", edit_company_path(@company, section: :communities),
          {remote: true, data: { toggle: "modal", target: '#modal-window' },  
          class: "btn btn-default btn-xs pull-right" } %>
    </div>
    <div class="panel-body">
      <table class="table table-condensed ero-table">
        <tr  style='font-weight: bold'>
          <td>Name</td>
          <td>Location</td>
        </tr>
        <% @company.communities.each do |community| %>
          <tr>
            <td><%= link_to community.name, community %></td>
            <td><%= community.location %></td>
          </tr>
        <% end %>
      </table>
    </div> 
  </div>
</div>
<div class="col-md-8">
    <div class="panel panel-default">
    <div class="panel-heading">
     Files
    </div>
    <div class="panel-body" id='#file-dropzone'>
      <table class="table table-condensed ero-table" id="files">
          <tr style='font-weight: bold;'>
            <th>Name</th>
            <th>Posted</th>
            <th>User</th>
          </tr>
          <tbody>
            <%= render partial: "data_files/file_list", locals: {object: @company} %>
          </tbody>
      </table>
      <div class="actions">
        <%#= f.submit %>
      </div>
      <%= form_for([@company, @data_file]) do |f| %>
        <div class="field">
          <%#= f.label :image %>
          <%= f.file_field :file, class: "file-button" %>
        
          <%= f.submit "Upload", class: 'btn btn-primary' %>
        </div>
      
        
      <% end %>
    </div> 
  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        Notes
      </div>
      <div class="panel-body">
        <table class="table table-condensed ero-table">
          <tr style='font-weight: bold'>
            <td>Date</td>
            <td>User</td>
            <td>Content</td>
          </tr>
        
        <% @company.notes.order(created_at: :asc).each do |note| %>
          <tr>
            <td><%= note.created_at.strftime("%m/%d/%Y %TZ") %></td>
            <td><%= note.user.try(:name) %></td>
            <td><%= sanitize nl2br(note.content) %></td>
          </tr>
        <% end %>
        </table>
        <%= link_to "#{fa_icon "plus-circle"} New".html_safe, company_new_note_path(@company, @note),
            {remote: true, data: { toggle: "modal", target: '#modal-window' },  
            class: "btn btn-primary" } %> 
      </div>
    </div>
  </div>
  

app/views/companies/_edit.html.erb
<% title = case params[:section]
    when "info"
      "Company Info"
    when "name"
      "Name"
    when "communities"
      "Communities"
end %>


<%= form_for(@company, remote: true) do |f| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 style="display:inline" class="modal-title"><%= "Edit " + title %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% case params[:section] %>
          <% when "communities" %>
            <div class="form-group row">
            <%= f.label :community, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :community, class: 'form-control', 
                  placeholder: "Community Name", id: "community" %>
              <%= f.hidden_field :community_id, id: "community_id" %>
            </div>
          </div>
          <% when "info" %>
          <div class="form-group row">
            <%= f.label :phone_number, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :phone_number, class: 'form-control', 
                  placeholder: "XXX-XXX-XXXX" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :fax, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :fax, class: 'form-control', 
                  placeholder: "XXX-XXX-XXXX" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :address, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :address_1, class: 'form-control', 
                  placeholder: "Street Address" %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-10 col-sm-offset-2">
              <%= f.text_field :address_2, class: 'form-control', 
                  placeholder: "Apt. or P.O. Box Number" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :zip, class: "col-sm-2 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :zip_code, class: 'form-control', 
                  placeholder: "5-digit Zip Code", id: "zip_code" %>
              <%= f.hidden_field :zip_code_id, :id => "zip_code_id" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :website, class: "col-sm-1 control-label" %>
            <div class="col-sm-6">
              <%= f.text_field :website, class: 'form-control',
                    placeholder: 'Website URL' %>
            </div>
          </div>
        <% when "name" %>
          <div class="form-group row">
            <div class="col-md-12">
              <div class="row">
              </div>
              <div class="row">
                <%= f.label :name, class: "col-sm-1 control-label" %>
                <div class="col-sm-5">
                  <%= f.text_field :name, class: 'form-control',
                        placeholder: 'Company Name' %>
                </div>
              </div>
            </div>
          </div>
        
        <% end %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Save Changes", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
<% end %>




<script>
  $(function () {
    $("#community").autocomplete({
      source: "/communities/autocomplete",
      minLength: 2,
      select: function(event, ui) {
        event.preventDefault();
        $("#community").val(ui.item.label);
        $("#community_id").val(ui.item.value);
      },
      focus: function(event, ui) {
        event.preventDefault();
        $("#community").val(ui.item.label);
      }
    });
    
    <% if @company.zip_code %>
      $( "#zip_code" ).val("<%= @company.zip_code.code %>");
      $( "#zip_code_id" ).val("<%= @company.zip_code.id %>");
    <% end %>
    $("#zip_code").autocomplete({
      source: "/zip_codes/autocomplete",
      minLength: 3,
      select: function(event, ui) {
        event.preventDefault();
        $("#zip_code").val(ui.item.label);
        $("#zip_code_id").val(ui.item.value);
      },
      focus: function(event, ui) {
        event.preventDefault();
        $("#zip_code").val(ui.item.label);
      }
    });
  });
</script>

app/views/companies/_new_note.html.erb
<%= form_for(@note, url: company_save_note_path([@company, @note]), remote: true) do |f| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 style="display:inline" class="modal-title">New Note</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group row">
          <div class="col-sm-12">
            <%= f.text_area(:content, cols: 20, rows: 20, 
                placeholder: "Enter note...", class: 'form-control',
                style: "overflow-y: scroll") %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
          <%= f.submit "Save Changes", class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
<% end %>

app/views/companies/_notes.html.erb
<div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Notes
        </div>
        <div class="panel-body">
          <table class="table table-condensed ero-table">
            <tr style='font-weight: bold'>
              <td>Date</td>
              <td>User</td>
              <td>Content</td>
            </tr>
          
          <% @company.notes.order(created_at: :asc).each do |note| %>
            <tr>
              <td><%= note.created_at.strftime("%m/%d/%Y %TZ") %></td>
              <td><%= note.user.try(:name) %></td>
              <td><%= sanitize nl2br(note.content) %></td>
            </tr>
          <% end %>
          </table>
          <%= link_to "#{fa_icon "plus-circle"} New".html_safe, company_new_note_path(@company, @note),
              {remote: true, data: { toggle: "modal", target: '#modal-window' },  
              class: "btn btn-primary" } %> 
        </div>
      </div>
  </div> 
  

app/views/companies/_search_results.html.erb
<table class="table table-condensed ero-table">
  <tr style='font-weight: bold'>
    <td>Name</td>
    <td>Communities</td>
    <td></td>
  </tr>


<% @companies.each do |company| %>
  <tr>
    <td><%= link_to company.name, company %></td>
    <td><%= company.communities_count %></td>
    <td><%= link_to "Delete", company, method: :delete,
                  data: { confirm: "Are you sure you want to delete #{company.name}?" },
                  class: "btn-sm btn-danger" if current_user.admin %></td>
  </tr>
<% end %>
</table>
<h6 style='margin-bottom: 1px'><%= page_entries_info @companies, :model => "companies" %></h6>
<%= will_paginate @companies, :param_name => 'page', :style => 'font-size: 9px; margin: 1px' %>
     

app/views/companies/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

app/views/companies/index.html.erb
<% provide(:title, 'Companies') %>

<div class="container">

  <h3><%= current_user.name %></h3>

  <h3>Companies <%= link_to "#{fa_icon "plus-circle"} New".html_safe, new_company_path,
                class: "btn btn-primary" %> </h3>
  <div class="form-group row">
    <div class="col-sm-4">
    <%= form_tag companies_path, :method => 'get', :id => "companies_search", class: "form-inline" do %>
      <%= text_field_tag :search, params[:search], class: 'form-control',
            placeholder: 'Name', id: "company" %>
      <%= submit_tag "Search", name: nil, class: 'btn btn-primary' %>
    <% end %>
    </div>
  </div>

  <div id="search_results">
    <%= render 'search_results' %>
  </div>
    
</div>

<script>
    
  $(function() {
    $("#companies_search input").keyup(function() {
      $.get($("#companies_search").attr("action"), $("#companies_search").serialize(), null, "script");
      return false;
    });
  });
</script>

app/views/companies/index.js.erb
$("#search_results").html("<%= escape_javascript(render("search_results")) %>");

app/views/companies/new.html.erb
<% provide(:title, "Create Company") %>
<h3 style='text-align: center'>Create a New Company</h3>
  
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@company) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        
          <%= f.text_field :name, class: 'form-control', 
              placeholder: "Company Name" %>

        <%= f.submit "Create Company", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/companies/new_note.js.erb
$("#modal-window").html("<%= escape_javascript(render 'new_note') %>");

app/views/companies/show.html.erb
<% provide(:title,"#{@company.name}") %>

<div id="company" class="container">
    <%= render(:partial => 'company') %>
</div>

<script>
  $("#file-upload").fileupload({
    add: function(e, data) {
      data.progressBar = $('<div class="progress" style="width: 300px"><div class="progress-bar"></div></div>').insertAfter(".actions");
      var options      = {
        extension: data.files[0].name.match(/(\.\w+)?$/)[0], // set the file extension
        _: Date.now() // prevent caching
      };

      $.getJSON("/data_files/upload/cache/presign", options, function(result) {
        data.formData  = result.fields;
        data.url       = result.url;
        data.paramName = "file";
        data.submit();
      });

    },

    progress: function(e, data) {
      var progress   = parseInt(data.loaded / data.total * 100, 10);
      var percentage = progress.toString() + '%';
      data.progressBar.find(".progress-bar").css("width", percentage).html(percentage);
    },

    done: function(e, data) {
      data.progressBar.remove();

      var file = {
        id:       data.formData.key.match(/cache\/(.+)/)[1], // we have to remove the prefix part
        storage:  'cache',
        metadata: {
          size:      data.files[0].size,
          filename:  data.files[0].name.match(/[^\/\\]+$/)[0], // IE return full path
          upload_options: {acl: 'authenticated-read' },
          mime_type: data.files[0].type
        }
      };

      var form      = $(this).closest("form");
      var form_data = new FormData(form[0]);
      form_data.append($(this).attr("name"), JSON.stringify(file));

      $.ajax(form.attr("action"), {
        contentType: false,
        processData: false,
        data:        form_data,
        method:      form.attr("method"),
        dataType:    "json",
        success: function(response) {
          var $div = $(
              '<td><a href="' + response.file_url + '">' + response.file_name + '</a></td>' +
              '<td>' + response.file_date + '</td>' +
              '<td>' + response.file_poster_name + '</td>'
            )
          
          function addRow(tableID) {
            // Get a reference to the table
            var tableRef = document.getElementById(tableID);
          
            // Insert a row in the table at row index 0
            var newRow = tableRef.insertRow(-1);
          
            // Insert a cell in the row at index 0
            var newCell1 = newRow.insertCell(0);
            var newCell2 = newRow.insertCell(1);
            var newCell3 = newRow.insertCell(2);
          
            // Append a text node to the cell
            var a = document.createElement('a');
            var newText1 = document.createTextNode(response.file_name);
            var newText2 = document.createTextNode(response.file_date);
            var newText3 = document.createTextNode(response.file_poster_name);
            
            a.appendChild(newText1);
            a.title = response.file_name;
            a.href = response.file_url;
            
            newCell1.appendChild(a);
            newCell2.appendChild(newText2);
            newCell3.appendChild(newText3);
            
          }

          // Call addRow() with the ID of a table
          addRow('files');
          
        }
      });
    }
  });
</script>

app/views/companies/update.js.erb
$(function () {
  $('#modal-window').modal('toggle');
  $('#company').html("<%= j render(partial: 'company') %>");
});