config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'static_pages#home'
#  mount Sidekiq::Web, at: '/sidekiq'
#  mount Resque::Server, :at => "/resque"
  mount Shrine.presign_endpoint(:cache) => "/data_files/upload/cache/presign"
  mount Shrine.presign_endpoint(:cache) => "/photos/upload/cache/presign"
  
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  
  get     'settings'         => 'static_pages#settings'
  get     'team'         => 'static_pages#team'
  get     'testimonials'         => 'static_pages#testimonials'
  get     'terms'         => 'static_pages#terms'
  get     'privacy'         => 'static_pages#privacy'
  get     'login'             => 'sessions#new'
  post    'login'             => 'sessions#create'
  delete  'logout'            => 'sessions#destroy'
  
  resources :journies do
    collection do 
      get :start
      get :living
      post :update_living
      get :medical
      post :update_medical
      get :budget
      post :update_budget
      get :veteran
      patch :update_veteran
      get :activities
      post :update_activities
      get :prospect_priorities
      post :update_prospect_priorities
      get :lead_priorities
      post :update_lead_priorities
      get :prospect_name
      patch :update_prospect_name
      get :lead_name
      get :update_lead_name
      patch :update_lead_name
      get :age
      post :update_age
      get :phone
      patch :update_phone
      get :validate_code
      post :check_code
      get :email
      patch :update_email
      get :rep
      get :location_search
      get :distance_search
      post :update_prospective_communities
    end
  end
  
  resources :users do
    get :password
    post :resend_activation_email
    patch :update_password
    
    collection do
      put :update_multiple
    end
  end
  
  resources :companies do
    resources :data_files
    get :new_note
    post :save_note
    collection do
      get :autocomplete
    end 
  end
  
  resources :pharmacies do
    get :new_note
    post :save_note
    collection do
    end
  end
  
  resources :contacts do
    resources :data_files
    get :distance_search
    get :community_search
    get :new_note
    get :new_result
    get :new_respite
    get :edit_result
    get :edit_finance
    get :decision_makers
    get :send_claim_email
    post :update_prospective_communities
    post :destroy_prospective_communities
    post :save_note
    post :save_result
    patch :save_result
    post :save_respite
    patch :save_finance
    patch :add_family
    put :update_decision_makers
    collection do
      get :autocomplete_resident
      get :autocomplete_family
      get :autocomplete_business
      get :autocomplete_clinician
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end

  resources :community_search, only: [:index, :show] do
    collection do
      post :index
      get :add_to_interest
      get :get_contact
      post :submit_contact
    end
  end

  resources :communities do
    resources :data_files
    resources :photos
    get :new_note
    post :save_note
    get :autocomplete_pharmacies
    collection do
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end
  
  resources :activities do
    collection do
      put :update_multiple
    end
  end
  resources :dinings do
    collection do
      put :update_multiple
    end
  end
  resources :positions do
    collection do
      put :update_multiple
    end
  end
  resources :features do
    collection do
      put :update_multiple
    end
  end
  resources :license_types do
    collection do
      put :update_multiple
    end
  end
  resources :result_types do
    collection do
      put :update_multiple
    end
  end
  resources :placement_statuses do
    collection do
      put :update_multiple
    end
  end
  resources :medicaid_providers do
    collection do
      put :update_multiple
    end
  end
  resources :zip_codes do
    collection do
      get :autocomplete
    end 
  end
  
  resources :cities do
    collection do
      get :autocomplete
      get :autocomplete_name
    end
  end
  
  resources :users,               except: [:destroy]
  resources :account_activations, only: [:edit]
  resources :validations, only: [:edit]
  resources :notes,               only: [:destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :photos, only: [:update]
end

app/models/community.rb
class Community < ActiveRecord::Base
  acts_as_taggable_on :activities, :features, :dinings, :undesireds
  attribute   :activity_list_tokens, :string
  attribute   :dining_list_tokens, :string
  attribute   :feature_list_tokens, :string
  attribute   :undesired_list_tokens, :string
  attribute   :open_since_input, :string
  attribute   :semi_private_availability, :integer
  attribute   :private_availability, :integer
  attribute   :clinician_search, :string
  attribute   :clinician_id, :integer
  
  before_create :create_account_number
  
  has_many :data_files, as: :fileable, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  belongs_to :company, counter_cache: true
  belongs_to :user
  belongs_to :executive_director, class_name: "Contact"
  belongs_to :nursing_director, class_name: "Contact"
  belongs_to :admissions_director, class_name: "Contact"
  belongs_to :marketing_director, class_name: "Contact"
  belongs_to :pharmacy, counter_cache: true
  belongs_to :zip_code
  has_many :availabilities, dependent: :destroy
  has_many :employees, class_name: "Contact", foreign_key: :community_id
  has_many :patients, class_name: "Contact", foreign_key: :facility_id
  
  has_many :community_activities, dependent: :destroy
  has_many :community_clinicians, dependent: :destroy
  has_many :clinicians, class_name: "Contact", through: :community_clinicians, source: :contact
  has_many :community_dinings, dependent: :destroy
  has_many :community_features, dependent: :destroy
  has_many :community_license_types, dependent: :destroy
  has_many :license_types, through: :community_license_types
  has_many :results, dependent: :destroy
  has_many  :prospective_communities, dependent: :destroy
  has_many  :leads, class_name: "Contact", through: :prospective_communities
  
  has_many :notes, as: :notable, dependent: :destroy
  has_many :community_medicaid_providers
  has_many :medicaid_providers, through: :community_medicaid_providers
  
  has_many :respite_stays
  
  monetize :semi_private_cents
  monetize :private_cents
  monetize :community_fee_cents
  monetize :respite_rate_cents
  monetize :adult_day_care_rate_cents
  monetize :pet_fee_cents
  monetize :second_person_fee_cents
  
  geocoded_by :full_street_address, if: ->(community){ community.address_1.present? and community.address_1_changed? }
  after_validation :geocode          # auto-fetch coordinates
  
  validates :name, presence: true, length: { maximum: 50 }

  def claim_email_contact
    marketing_director || admissions_director || executive_director
  end

  def send_claim_email(prospect_id, lead_id)
    ContactMailer.lead(self, prospect_id, lead_id).deliver_now
  end
  
  def self.with_licenses(license_ids)
    where("NOT EXISTS (SELECT * FROM license_types
      WHERE NOT EXISTS (SELECT * FROM community_license_types
        WHERE community_license_types.license_type_id = license_types.id
        AND community_license_types.community_id = communities.id)
      AND license_types.id IN (?))", license_ids)
  end
  
  def location
    "#{zip_code.city.name}, #{zip_code.city.county.state.two_digit_code}" if zip_code
  end
  
  def full_street_address
    if address_1 && zip_code
      [address_1, zip_code.city.name, zip_code.city.county.state.name, 'US'].compact.join(', ')
    end
  end
  
  def activity_list_tokens=(tokens)
    tags = []
    tokens.split(',').each do |token|
      tag = ActsAsTaggableOn::Tag.find_by_id(token.to_i)
      if tag.nil?
        name = token.gsub!(/<<<(.+?)>>>/) { $1 }
      else
        name = tag.name
      end
      tags << name
    end
    self.activity_list = tags
  end
  
  def dining_list_tokens=(tokens)
    tags = []
    tokens.split(',').each do |token|
      tag = ActsAsTaggableOn::Tag.find_by_id(token.to_i)
      if tag.nil?
        name = token.gsub!(/<<<(.+?)>>>/) { $1 }
      else
        name = tag.name
      end
      tags << name
    end
    self.dining_list = tags
  end
  
  def feature_list_tokens=(tokens)
    tags = []
    tokens.split(',').each do |token|
      tag = ActsAsTaggableOn::Tag.find_by_id(token.to_i)
      if tag.nil?
        name = token.gsub!(/<<<(.+?)>>>/) { $1 }
      else
        name = tag.name
      end
      tags << name
    end
    self.feature_list = tags
  end
  
  def undesired_list_tokens=(tokens)
    tags = []
    tokens.split(',').each do |token|
      tag = ActsAsTaggableOn::Tag.find_by_id(token.to_i)
      if tag.nil?
        name = token.gsub!(/<<<(.+?)>>>/) { $1 }
      else
        name = tag.name
      end
      tags << name
    end
    self.undesired_list = tags
  end
  
  def self.search(search)
    if search
      where('name ilike ?', "%#{search}%")
    else
      nil
    end
  end
  
  private
    def create_account_number
      begin
        self.account_number = SecureRandom.hex(4).upcase
      end while Community.where(account_number: self.account_number).exists?
    end
end

app/controllers/community_search_controller.rb
class CommunitySearchController < ApplicationController
  before_action :set_community, only: [:show]

  def get_contact
    @contact = Contact.new
  end

  def submit_contact
    user = User.find_by(email: 'troy@sotercares.com')
    @contact = Contact.new(
        first_name: params[:contact][:first_name],
        last_name: params[:contact][:last_name],
        contact_type: "Resident",
        user: user,
        cell_phone: params[:contact][:cell_phone],
        email: params[:contact][:email],
        web_lead: true
    )

    if @contact.save
      SendContact.perform_async(
          user.id,
          session[:medicaid_provider_ids],
          session[:medical_needs],
          session[:activity_tags],
          session[:dining_tags],
          session[:interest_ids],
          @contact.id
      )

      render 'close_modal'
    else
      flash[:danger] = 'Please check information'
      render 'get_contact'
    end
  end

  def show
  end
  
  def index
    if session[:interest_ids].present?
      session[:interest__ids] = Community.where(id: session[:interest_ids]).distinct.pluck(:id)
      session[:interest_ids] += Community.where(id: params[:community_id]).distinct.pluck(:id) if params[:community_id].present?
    elsif params[:community_id].present?
      session[:interest_ids] = Community.where(id: params[:community_id]).distinct.pluck(:id)
    else
      session[:interest_ids] = []
    end

    if params[:remove_id].present?
      session[:interest_ids].delete(params[:remove_id].to_i)
    end

    @interest_communities = Community.where(id: session[:interest_ids]).distinct
    respond_to do |format|
      format.js
      format.html {
        session[:budget] = params[:budget] if params[:budget].present?
        budget = session[:budget].to_i
        budget = 10000000 if budget == 0
        session[:budget] = budget
        if params[:distance].present?
          session[:distance] = params[:distance]
        elsif session[:distance].nil?
          session[:distance] = 10
        end

        if params[:medicaid_provider_ids].present?
          session[:medicaid_provider_ids] = params[:medicaid_provider_ids]
        else
          session[:medicaid_provider_ids] = nil
        end

        if params[:city].present?
          city_name = params[:city]
        elsif session[:city].blank?
          results = Geocoder.search(remote_ip())
          city_name = results.first.city + ', ' + results.first.region_code
        else
          city_name = session[:city]
        end

        city_search = city_name.try { strip.split(',')[0].strip.titlecase }
        state_search = city_name.try { strip.split(',')[1].try { strip.upcase } }
        city_length = city_search.length
        state_length = state_search.length if state_search

        if state_search.present?
          city = City.find_by_id(City.fetch_city_list.select{ |hash| hash["name"].first(city_length) == city_search and
              hash["state"].first(state_length) == state_search
          }.first["id"])
        else
          city = City.find_by_id(City.fetch_city_list.select{ |hash| hash["name"].first(city_length) == city_search }.first["id"])
        end

        session[:city] = city.name + ', ' + city.state

        if params[:medical_needs].present?
          session[:medical_needs] = params[:medical_needs]
        else
          session[:medical_needs] = nil
        end

        if session[:medical_needs].present?
          license_ids = LicenseType.tagged_with(ActsAsTaggableOn::Tag.where(id: params[:medical_needs]), on: :licenses, any: true).pluck(:id)
          if session[:medicaid_provider_ids].present?
            @communities = Community.with_licenses(license_ids).where.not(zip_code: nil).where('semi_private_cents <= ? OR private_cents <= ?', budget, budget).near(session[:city], session[:distance].to_i)
                               .joins(:medicaid_providers).where(medicaid_providers: { id: session[:medicaid_provider_ids] }).distinct
          else
            @communities = Community.with_licenses(license_ids).where.not(zip_code: nil).where('semi_private_cents <= ? OR private_cents <= ?', budget, budget).near(session[:city], session[:distance].to_i).distinct
          end

        else
          if session[:medicaid_provider_ids].present?
            @communities = Community.where.not(zip_code: nil).where('semi_private_cents <= ? OR private_cents <= ?', budget, budget).near(session[:city],  session[:distance].to_i)
                               .joins(:medicaid_providers).where(medicaid_providers: { id: session[:medicaid_provider_ids] }).distinct
          else
            @communities = Community.where.not(zip_code: nil).where('semi_private_cents <= ? OR private_cents <= ?', budget, budget).near(session[:city],  session[:distance].to_i).distinct
          end
        end

        if params[:activities].present?
          session[:activities] =  params[:activities]
        else
          session[:activities] = nil
        end

        if params[:dining].present?
          session[:dining] = params[:dining]
        else
          session[:dining] = nil
        end

        session[:activity_tags] = [] if session[:activities].nil?
        session[:dining_tags] = [] if session[:dining].nil?
        session[:activity_tags] = ActsAsTaggableOn::Tag.where(id: params[:activities]).pluck(:name) if params[:activities]
        session[:dining_tags] = ActsAsTaggableOn::Tag.where(id: params[:dining]).pluck(:name) if params[:dining]
        if session[:activity_tags].present? && session[:dining_tags].blank?
          tags = session[:activity_tags]
          @communities = @communities.sort_by { |o| -(tags & (o.dining_list + o.activity_list + o.feature_list + o.undesired_list)).length }.paginate(page: params[:page], :per_page => 5)
        elsif session[:activity_tags].blank? && session[:dining_tags].present?
          tags = session[:dining_tags]
          @communities = @communities.sort_by { |o| -(tags & (o.dining_list + o.activity_list + o.feature_list + o.undesired_list)).length }.paginate(page: params[:page], :per_page => 5)
        elsif session[:activity_tags].present? && session[:dining_tags].present?
          tags = session[:activity_tags] + session[:dining_tags]
          @communities = @communities.sort_by { |o| -(tags & (o.dining_list + o.activity_list + o.feature_list + o.undesired_list)).length }.paginate(page: params[:page], :per_page => 5)
        else
          @communities = @communities.paginate(page: params[:page], :per_page => 5)
        end
      }
    end

  rescue
    @communities = Community.where(name: nil).paginate(page: params[:page], :per_page => 5)
    flash.now[:danger] = 'Please enter a valid value'
    render 'index'
  end
  
  private
    def send_email
      user = User.find_by(email: 'troy@sotercares.com')
      message = "WEBSITE LEAD\n"
      message += "MEDICAID PROVIDERS:\n"
      MedicaidProvider.where(id: session[:medicaid_provider_ids]).each do |mp|
        message += mp.name + "\n"
      end
      message += "\nMedical Needs:\n"
      message += ActsAsTaggableOn::Tag.where(id: session[:medical_needs]).pluck(:name).join(', ')
      message += "\nActivities:\n"
      message += session[:activity_tags].join(',') + "\n"
      message += "\nLanguages:\n"
      message += session[:dining_tags].join(', ') + "\n"

      message += "\nINTERESTED COMMUNITIES\n"
      interest_communities = Community.where(id: session[:interest_ids]).distinct
      @contact.prospects << interest_communities
      interest_communities.each do |community|
        message += community.name + '-' + community.id.to_s + "\n"
      end

      @contact.results << Result.new(result_type: ResultType.find_by(name: "Qualified, OK to pursue"))

      user.send_notification_email(message)
    end

    def set_community
      @community = Community.find_by_id(params[:id]) || Community.find_by_id(params[:community_id])
    end
end

app/views/community_search/_communities.html.erb
<div class="card h-100">
  <h6 style='margin-bottom: 1px'><%= page_entries_info @communities, :model => "communities" %></h6>
  <%= will_paginate @communities, params: params.reject{|k,v| k == 'authenticity_token' }, param_name: 'page', :style => 'font-size: 9px; margin: 1px' %>
  <% @communities.each do |community| %>
    <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
      <%= community.name %>
      <%= link_to "#{fa_icon "plus-circle"} Interest List".html_safe, community_search_index_path(community_id: community.id),
                  {remote: true, class: "btn btn-sm btn-primary" } %>
      <span class="community-address pull-right"><%= community.address_1 %><br><%= community.zip_code.try { city.name } %>, <%= community.zip_code.try { city.state } %></span>
    </h4>


  <div class="card-body">
    <div class="row">
      <% community.photos.where(viewable: true).first(1).each do |photo| %>
        <div class="col-sm-2">
          <% disposition = "attachment; filename=#{photo.image.original_filename.inspect}" %>
          <%= image_tag(photo.image.url(response_content_disposition: disposition,
                                        virtual_host: true, host: "https://storage.sotercares.com"), class: "img-responsive") %>

          <% if community.photos.where(viewable: true).size > 1 %>
            <%= link_to "More Pictures", community_search_path(community),
                        {remote: true, data: { toggle: "modal", target: '#modal-window' },
                         class: "btn btn-default btn-xs" } %>
          <% end %>
        </div>
    <% end %>
      <div class="col-sm-10">
        <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
          <span style="font-weight: bold">Licenses:</span> <%= community.license_types.pluck(:name).join(", ") %><br>
          <span style="font-weight: bold">Languages:</span> <%= highlight(((session[:dining_tags] & community.dining_list) + (community.dining_list.first(5) - session[:dining_tags])).join(", "), session[:dining_tags]) %>
          <span style="font-weight: bold"><%= "and #{community.dining_list.size - 5 - session[:dining_tags].size} more..." if (session[:dining_tags].size + 5) < community.dining_list.size %></span><br>
          <span style="font-weight: bold">Interests and Activities:</span> <%= highlight(((session[:activity_tags] & community.activity_list) + (community.activity_list.first(10) - session[:activity_tags])).join(", "), session[:activity_tags]) %>
          <span style="font-weight: bold"><%= "and #{community.activity_list.size - 10 - session[:activity_tags].size} more..." if (session[:activity_tags].size + 10) < community.activity_list.size %></span><br>
          <% if community.private_cents > 0 %>
            <span style="font-weight: bold">Private Rate:</span><%= number_to_currency(community.private) %> <br>
          <% end %>
          <% if community.semi_private_cents > 0 %>
            <span style="font-weight: bold">Semi-Private Rate:</span><%= number_to_currency(community.semi_private) %> <br>
          <% end %>
          <% if community.youtube_identifier.present? %>
            <span style="font-weight: bold">Video Tour:</span><br>
            <iframe width="280" height="158" src="https://www.youtube.com/embed/<%= community.youtube_identifier %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/community_search/_contact.html.erb
<%= form_for(@contact, url: submit_contact_community_search_index_path, id: 'frm', remote: true) do |f| %>
  <div class="modal-dialog" style="overflow-y: initial !important" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 style="display:inline" class="modal-title">Contact me about my list</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control', placeholder: 'Your first name' %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control', placeholder: 'Your last name' %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control', placeholder: 'john@example.com' %>

        <%= f.label :cell_phone %>
        <%= f.text_field :cell_phone, class: 'form-control', placeholder: '323-555-1212' %>
      </div>
      <div class="modal-footer">
        <div class="pull-left">
          <%= link_to "Privacy Policy", privacy_path %>
          |
          <%= link_to "Terms of Use", terms_path %>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Sending..." }, id: 'send' %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
<% end %>

app/views/community_search/_interest_list.html.erb
<div class="card h-100">
  <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">My Interest List</h4>
  <div class="card-body">
    <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
      <% if @interest_communities.empty? %>
        <span style="font-style: italic">Add communities that interest you to the list...</span>
      <% end %>
      <% @interest_communities.each do |community| %>
        <%= link_to "#{fa_icon "close"}".html_safe, community_search_index_path(
            remove_id: community.id,
            ),
                    {remote: true, class: "", style: "color: red" } %>
        <%= community.name %>
        <br>
      <% end %>
    </p>
      <%= link_to "Get Pricing and Availability", get_contact_community_search_index_path,
                  {remote: true, data: { toggle: "modal", target: '#modal-window' },
                   class: "btn btn-success btn-block" } %>
  </div>
</div>

app/views/community_search/close_modal.js.erb
$("#modal-window").html("<%= escape_javascript(render 'thank_you') %>");

app/views/community_search/get_contact.js.erb
$("#modal-window").html("<%= escape_javascript(render 'contact') %>");

app/views/community_search/index.html.erb
<div class="info-box">
  <div class="row">
    <div class="col-lg-4 mb-12">
      <div class="col-sm-12" id="interest_list">
        <%= render 'interest_list' %>
      </div>
      <%= form_tag(community_search_index_path) do %>
      <div class="col-sm-6">
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Searching within <%= session[:distance] %> miles of <%= session[:city] %></h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
              <%= text_field_tag :city, nil, { placeholder: "New city", class: 'text-center', style: 'width: 100%', id: 'city', onchange: 'this.form.submit();' } %>
              <%= number_field_tag :distance, nil, { placeholder: "Change distance", class: 'text-center', style: 'width: 100%', id: 'distance', onchange: 'this.form.submit();' } %>
            </p>
          </div>
        </div>
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Medicaid Providers</h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">

              <%= select_tag :medicaid_provider_ids,
                             options_from_collection_for_select(MedicaidProvider.all,
                                                                :id, :name, session[:medicaid_provider_ids]), multiple: true, style: 'width: 100%', id: 'provider_list', onchange: 'this.form.submit();' %>

            </p>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Budget</h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">

              <%= radio_button_tag :budget, 250000, session[:budget] == 250000, onchange: 'this.form.submit();' %> Up to $2500<br>
              <%= radio_button_tag :budget, 300000, session[:budget] == 300000, onchange: 'this.form.submit();' %> Up to $3000<br>
              <%= radio_button_tag :budget, 350000, session[:budget] == 350000, onchange: 'this.form.submit();' %> Up to $3500<br>
              <%= radio_button_tag :budget, 400000, session[:budget] == 400000, onchange: 'this.form.submit();' %> Up to $4000<br>
              <%= radio_button_tag :budget, 450000, session[:budget] == 450000, onchange: 'this.form.submit();' %> Up to $4500<br>
              <%= radio_button_tag :budget, 500000, session[:budget] == 500000, onchange: 'this.form.submit();' %> Up to $5000<br>
              <%= radio_button_tag :budget, 550000, session[:budget] == 550000, onchange: 'this.form.submit();' %> Up to $5500<br>
              <%= radio_button_tag :budget, 600000, session[:budget] == 600000, onchange: 'this.form.submit();' %> Up to $6000<br>
              <%= radio_button_tag :budget, 10000000, session[:budget] == 10000000, onchange: 'this.form.submit();' %> More than $6000<br>
            </p>
          </div>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Medical Needs</h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">

                <%= select_tag :medical_needs,
                               options_from_collection_for_select(TaggingManual.tokens('licenses', nil),
                                                                  :id, :name, session[:medical_needs]), multiple: true, style: 'width: 100%', id: 'licenses_list', onchange: 'this.form.submit();' %>
            </p>
          </div>
        </div>
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Interests and Activities</h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">

              <%= select_tag :activities,
                             options_from_collection_for_select(TaggingManual.tokens('activities', nil),
                                                                :id, :name, session[:activities]), multiple: true, style: 'width: 100%', id: 'activities_list', onchange: 'this.form.submit();' %>
            </p>
          </div>
        </div>
        <div class="card h-100">
          <h4 class="card-header" style="color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Languages</h4>
          <div class="card-body">
            <p class="card-text" style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">

              <%= select_tag :dining,
                             options_from_collection_for_select(TaggingManual.tokens('dinings', nil),
                                                                :id, :name, session[:dining]), multiple: true, style: 'width: 100%', id: 'dining_list', onchange: 'this.form.submit();' %>
            </p>
          </div>
        </div>
      </div>
    <% end %>

    </div>

    <div class="col-lg-8 mb-12">
      <div class="col-sm-12" id="communities">
        <%= render 'communities' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#city").autocomplete({
      source: "/cities/autocomplete_name",
      minLength: 3,
      select: function(event, ui) {
          event.preventDefault();
          $("#city").val(ui.item.label);
      },
      focus: function(event, ui) {
          event.preventDefault();
          $("#city").val(ui.item.label);
      }
  });
  $('#licenses_list').select2({
      theme: "bootstrap"
  });
  $('#dining_list').select2({
      theme: "bootstrap"
  });
  $('#activities_list').select2({
      theme: "bootstrap"
  });
  $('#provider_list').select2({
      theme: "bootstrap"
  });
  // Activate Carousel
  $("#myCarousel").carousel();

  // Enable Carousel Indicators
  $(".item").click(function(){
      $("#myCarousel").carousel(1);
  });

  // Enable Carousel Controls
  $(".left").click(function(){
      $("#myCarousel").carousel("prev");
  });
</script>

app/views/community_search/index.js.erb
$(function () {
    $('#interest_list').html("<%= j render(partial: 'interest_list') %>");
});

app/views/community_search/show.js.erb
$("#modal-window").html("<%= escape_javascript(render 'show') %>");