config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'static_pages#home'
#  mount Sidekiq::Web, at: '/sidekiq'
#  mount Resque::Server, :at => "/resque"
  mount Shrine.presign_endpoint(:cache) => "/data_files/upload/cache/presign"
  mount Shrine.presign_endpoint(:cache) => "/photos/upload/cache/presign"
  
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new
  
  get     'settings'         => 'static_pages#settings'
  get     'team'         => 'static_pages#team'
  get     'testimonials'         => 'static_pages#testimonials'
  get     'terms'         => 'static_pages#terms'
  get     'privacy'         => 'static_pages#privacy'
  get     'login'             => 'sessions#new'
  post    'login'             => 'sessions#create'
  delete  'logout'            => 'sessions#destroy'
  
  resources :journies do
    collection do 
      get :start
      get :living
      post :update_living
      get :medical
      post :update_medical
      get :budget
      post :update_budget
      get :veteran
      patch :update_veteran
      get :activities
      post :update_activities
      get :prospect_priorities
      post :update_prospect_priorities
      get :lead_priorities
      post :update_lead_priorities
      get :prospect_name
      patch :update_prospect_name
      get :lead_name
      get :update_lead_name
      patch :update_lead_name
      get :age
      post :update_age
      get :phone
      patch :update_phone
      get :validate_code
      post :check_code
      get :email
      patch :update_email
      get :rep
      get :location_search
      get :distance_search
      post :update_prospective_communities
    end
  end
  
  resources :users do
    get :password
    post :resend_activation_email
    patch :update_password
    
    collection do
      put :update_multiple
    end
  end
  
  resources :companies do
    resources :data_files
    get :new_note
    post :save_note
    collection do
      get :autocomplete
    end 
  end
  
  resources :pharmacies do
    get :new_note
    post :save_note
    collection do
    end
  end
  
  resources :contacts do
    resources :data_files
    get :distance_search
    get :community_search
    get :new_note
    get :new_result
    get :new_respite
    get :edit_result
    get :edit_finance
    get :decision_makers
    get :send_claim_email
    post :update_prospective_communities
    post :destroy_prospective_communities
    post :save_note
    post :save_result
    patch :save_result
    post :save_respite
    patch :save_finance
    patch :add_family
    put :update_decision_makers
    collection do
      get :autocomplete_resident
      get :autocomplete_family
      get :autocomplete_business
      get :autocomplete_clinician
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end

  resources :community_search, only: [:index, :show] do
    collection do
      post :index
      get :add_to_interest
      get :get_contact
      post :submit_contact
    end
  end

  resources :communities do
    resources :data_files
    resources :photos
    get :new_note
    post :save_note
    get :autocomplete_pharmacies
    collection do
      get :autocomplete
      get :activities, as: :activities
      get :dinings, as: :dinings
      get :features, as: :features
      get :undesireds, as: :undesireds
      get :licenses, as: :licenses
    end 
  end
  
  resources :activities do
    collection do
      put :update_multiple
    end
  end
  resources :dinings do
    collection do
      put :update_multiple
    end
  end
  resources :positions do
    collection do
      put :update_multiple
    end
  end
  resources :features do
    collection do
      put :update_multiple
    end
  end
  resources :license_types do
    collection do
      put :update_multiple
    end
  end
  resources :result_types do
    collection do
      put :update_multiple
    end
  end
  resources :placement_statuses do
    collection do
      put :update_multiple
    end
  end
  resources :medicaid_providers do
    collection do
      put :update_multiple
    end
  end
  resources :zip_codes do
    collection do
      get :autocomplete
    end 
  end
  
  resources :cities do
    collection do
      get :autocomplete
      get :autocomplete_name
    end
  end
  
  resources :users,               except: [:destroy]
  resources :account_activations, only: [:edit]
  resources :validations, only: [:edit]
  resources :notes,               only: [:destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :photos, only: [:update]
end

app/controllers/journies_controller.rb
class JourniesController < ApplicationController
  before_action :set_contacts, except: [:start, :living]
  before_action :validated_user, only: [:location_search]
  
  def update_prospective_communities
    @community = Community.find_by_id(params[:community_id])
    @prospect.prospects << @community
    @prospect.notes << Note.new(content: "Community #{@community.name}(ID: #{@community.id}) sent claim email")
    @community.send_claim_email(@prospect.id, @lead.id)
  end 
  
  def distance_search
    city = City.find_by_id(params[:city_id])
    if @prospect.license_list.present?
      license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
      @communities = Community.with_licenses(license_ids).near("#{city.name}, #{city.county.state.two_digit_code}", params[:distance].to_i)
    else
      @communities = Community.near("#{city.name}, #{city.county.state.two_digit_code}", params[:distance].to_i)
    end
    tags = @prospect.dining_list + @prospect.activity_list + @prospect.feature_list + @prospect.undesired_list
    @communities = @communities.sort_by { |o| -(tags & (o.dining_list + o.activity_list + o.feature_list + o.undesired_list)).length }                  
  #  @activities = Community.tag_counts_on(:activities)
  end
  
  def start
  end
  
  def living
    @prospect = Contact.new(contact_type: "Resident", first_name: "Unknown", last_name: "Unknown")
    unless params[:self_guided] && params[:self_guided] == true
      @lead = Contact.create(contact_type: "Family", first_name: "Unknown", last_name: "Unknown")
      @prospect.relationships << Relationship.new(relationship_type: RelationshipType.find_by_id(params[:relationship_type_id]), relation: @lead)
      @prospect.gender = params[:gender] if params[:gender] == "Male" || params[:gender] == "Female"
      @prospect.save
    else
      @lead = @prospect
    end
  end
  
  def update_living
    @prospect.notes << Note.new(content: params[:home_alone]) if params[:home_alone]
    @prospect.notes << Note.new(content: params[:home_with_spouse]) if params[:home_with_spouse]
    @prospect.notes << Note.new(content: params[:friend]) if params[:friend]
    @prospect.notes << Note.new(content: params[:family]) if params[:family]
    @prospect.notes << Note.new(content: params[:rehab]) if params[:rehab]
    @prospect.notes << Note.new(content: params[:hospital]) if params[:hospital]
    @prospect.notes << Note.new(content: params[:state]) if params[:state]
    redirect_to medical_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def medical
    
  end
  
  def update_medical
    @prospect.assign_attributes(new_license_list_tokens: params[:new_license_list_tokens])
    @prospect.save
    redirect_to budget_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def budget
    @finance = Finance.new
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_budget
    @prospect.finance = Finance.create(finance_params)
    redirect_to veteran_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def veteran
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_veteran
    @prospect.update(contact_params)
    redirect_to activities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def activities
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_activities
    @prospect.assign_attributes(new_activity_list_tokens: params[:new_activity_list_tokens])
    @prospect.save
    redirect_to prospect_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def prospect_priorities
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def lead_priorities
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_prospect_priorities
    @prospect.notes << Note.new(content: params[:priority] + " most important to Prospect.")
    if @lead == @prospect
      redirect_to prospect_name_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    else
      redirect_to lead_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    end
  end
  
  def update_lead_priorities
    @prospect.notes << Note.new(content: params[:priority] + " most important to Family.")
    redirect_to lead_name_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def prospect_name
    @prospect.first_name = nil
    @prospect.last_name = nil
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def lead_name
    @lead.first_name = nil
    @lead.last_name = nil
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_lead_name
    if @lead.update(contact_params)
      redirect_to prospect_name_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    else
      license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
      @communities = Community.with_licenses(license_ids)
      render :lead_name
    end
  end
  
  def update_prospect_name
    if @prospect.update(contact_params)
      redirect_to age_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    else
      license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
       @communities = Community.with_licenses(license_ids)
      render :prospect_name
    end
  end
  
  def age
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_age
    @prospect.notes << Note.new(content: "Prospect age: " + params[:age])
    redirect_to phone_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
  end
  
  def phone
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_phone
    if @lead.update(contact_params)
      if @lead.cell_phone.present?
        @lead.send_code
        redirect_to validate_code_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
      else
        redirect_to email_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
      end
    else
      license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
      @communities = Community.with_licenses(license_ids)
      render :phone
    end
  end
  
  def validate_code
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def check_code
    if params[:code] == @lead.phone_code
      @lead.update(validated: true)
      flash[:success] = "Cell phone validated"
      redirect_to email_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    else
      flash[:danger] = "Invalid code"
      redirect_to phone_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
    end
  end
  
  def email
    license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
    @communities = Community.with_licenses(license_ids)
  end
  
  def update_email
    if @lead.update(contact_params)
      if @lead.email.present?
        @lead.send_validation_email(@prospect.id)
        redirect_to rep_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
      elsif @lead.validated?
        redirect_to rep_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
      else
        flash[:danger] = "Either a valid cell phone or email must be provided"
        redirect_to phone_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)
      end
    else
      license_ids = LicenseType.tagged_with(@prospect.license_list, on: :licenses, any: true).pluck(:id)
      @communities = Community.with_licenses(license_ids)
      render :email
    end
  end
  
  def rep
    UserMailer.initial_lead("info@sotercares.com", @prospect.id, @lead.id).deliver_now
    @prospect.results << Result.new(result_type: ResultType.find_by(name: "Qualified, OK to pursue"))
  end
  
  def location_search
    @communities = []
  end
  
  private
    def validated_user
      redirect_to root_url, flash: { danger: "Authorization failure" } unless @lead.validated?
    end
  
    def finance_params
      params.require(:finance).permit!
    end
    
    def set_contacts
      @prospect = Contact.find_by_id(params[:prospect_id])
      @lead = Contact.find_by_id(params[:lead_id])
    end
    
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :cell_phone, :home_phone, :work_phone, :email,
        :license_list_tokens, :veteran, :activity_list_tokens)
    end
end

app/views/journies/_community_results.html.erb
<% if @communities.any? %>
  <hr>
  <div class="row">
    <div class="col-md-12 col-md-offset-3">
      <div id="map" style="width: 800px; height: 400px; max-width: 100%"></div>
    </div>
  </div>
  <hr>
<% end %>
<% x = 1 %>
<% @communities.first(9).each do |community| %>
<br>
<div class="container info-box">
  <div class="row">
  <div class="col-md-6">
    <h3 style='display: inline'><%= image_tag("https://cdn.sotercares.com/markers/marker-#{x}.png") %>  <%= community.name %></h3>
    <em> - <%= community.zip_code.city.name %>, <%= community.zip_code.city.county.state.two_digit_code %></em>
  </div>
  <div class="col-md-6">
    <%= link_to "Pricing", update_prospective_communities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id, community_id: community.id),
          {remote: true, data: { toggle: "modal", target: '#modal-window' },
          class: "btn btn-success btn-sm pull-right", method: :post } %>
   </div> 
  </div> 
    <hr>
    <div class="row">
      <% community.photos.where(viewable: true).each do |photo| %>
        <div class="col-sm-2">
              <% disposition = "attachment; filename=#{photo.image.original_filename.inspect}" %>
              <% if Rails.env.production? %>
                <%= image_tag(photo.image.url(response_content_disposition: disposition, 
                        virtual_host: true, host: "https://storage.sotercares.com"), class: "img-responsive") %>
              <% else %>
                <%= image_tag(photo.image.url(response_content_disposition: disposition), class: "img-responsive") %>
              <% end %>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-1">
        <strong>Activities:</strong>
      </div>
      <div class="col-md-5">
        <%= highlight(community.activity_list.join(", "), @prospect.activity_list, highlighter: '<em style="color: blue; font-weight: bold">\1</em>') %>
      </div>
      <div class="col-md-1">
        <strong>Languages:</strong>
      </div>
      <div class="col-md-5">
        <%= highlight(community.dining_list.join(", "), @prospect.dining_list, highlighter: '<em style="color: blue; font-weight: bold">\1</em>') %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">
        <strong>Features:</strong>
      </div>
      <div class="col-md-5">
        <%= highlight(community.feature_list.join(", "), @prospect.feature_list, highlighter: '<em style="color: blue; font-weight: bold">\1</em>') %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2"><strong>Transportation:</strong></div>
      <div class="col-md-4">
        <%= if community.transport?
                "Yes"
                else
                "No" 
                end %>
      </div>
    </div> 
    <div class="row">
      <div class="col-md-2"><strong>Pets:</strong></div>
      <div class="col-md-4">
        <%= if community.pets?
                "Yes"
                else
                "No" 
                end %>
      </div>
    </div>    
    <div class="row">    
    
     </div>
</div>
<% x += 1 %>
<% end %>
<br>
<script>
    new GMaps({
        div: '#map',
        lat: -12.043333,
        lng: -77.028333
    });
</script>

app/views/journies/activities.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif; font-size: 40px">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    There are a total of <strong><%= @communities.count %> communities</strong> that are potential matches.
    <% if @lead == @prospect %>
      What activities do you enjoy?
    <% else %>
      <% case @prospect.gender %>
      <% when "Male" %>
        <% relation =  @prospect.relationships.find_by(relation: @lead).relationship_type.male_name %>
      <% when "Female" %>
        <% relation =  @prospect.relationships.find_by(relation: @lead).relationship_type.female_name %>
      <% else %>
        <% relation = "Loved One" %>
      <% end %>
      What activities does your <%= relation %> enjoy?
    <% end %>
  </p>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Begin typing the activities in the box and we will display a list of options from which to pick. Add as many as you need.</p>
  <div class="row">
    <div class="col-sm-10">
      <%= form_tag(update_activities_journies_path) do %>
        <%= select_tag :new_activity_list_tokens,
                options_from_collection_for_select(TaggingManual.tokens('activities', params[:q]), 
                    :id, :name), multiple: true, class: "col-md-12", id: 'activities_list' %>
         <%= hidden_field_tag :prospect_id, @prospect.id %>
        <%= hidden_field_tag :lead_id, @lead.id %>
        <div><%= submit_tag 'Next', class: 'btn btn-primary' %></div>
      <% end %>
    </div>
  </div>
</div>
<br>

<script type="text/javascript">
    $(document).on('turbolinks:load', function() {
      $('#activities_list').select2({
        theme: "bootstrap"
      });
    });
</script>

app/views/journies/budget.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif; font-size: 40px">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    There are a total of <strong><%= @communities.count %> communities</strong> that are potential matches. Please tell us a little about your budget to help narrow your search.
  </p>

<%= form_for(@finance, url: update_budget_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)) do |f| %>
    <div class="row">
      <div class="col-md-6">
          <table class="table table-condensed ero-table">
            <tr>
              <td style='font-weight: bold'>Savings:</td>
              <td><div class="input-group">
                    <div class="input-group-addon">$</div>
                      <%= f.text_field :savings, class: 'form-control', id: 'result_date', placeholder: 'Amount' %>
                  </div>
              </td>
            </tr>
            <tr>
              <td style='font-weight: bold'>Pension/Annuity:</td>
              <td><div class="input-group">
                    <div class="input-group-addon">$</div>
                      <%= f.text_field :pension_annuity, class: 'form-control', id: 'result_date', placeholder: 'Amount' %>
                  </div>
              </td>
            </tr>
            <tr>
              <td style='font-weight: bold'>Social Security:</td>
              <td><div class="input-group">
                    <div class="input-group-addon">$</div>
                      <%= f.text_field :social_security, class: 'form-control', id: 'result_date', placeholder: 'Amount' %>
                  </div>
              </td>
            </tr>
          </table>
        </div>
      </div>
          <%= f.submit "Next", class: "btn btn-primary" %>
<% end %>

</div>
<br>

app/views/journies/distance_search.js.erb
$(function () {
  $('#communities').html("<%= j render(partial: 'community_results') %>");
});

app/views/journies/lead_name.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif; font-size: 40px">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    There are a total of <strong><%= @communities.count %> communities</strong> that are potential matches. <br>
    
    What is your name?
  </p>

<%= form_for(@lead, url: update_lead_name_journies_path(prospect_id: @prospect.id, lead_id: @lead.id)) do |f| %>
   <% if @lead.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@lead.errors.count, "error") %>.
    </div>
    <ul>
    <% @lead.errors.full_messages.each do |msg| %>
    <li id="error"><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-6">
          <div class="form-group row">
            <div class="col-sm-12 col-sm-offset-4">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
            </div>
            <div class="col-sm-12 col-sm-offset-4">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
            </div>
          </div>
        </div>
      </div>
          <%= f.submit "Next", class: "btn btn-primary" %>
<% end %>

</div>
<br>

app/views/journies/lead_priorities.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    There are a total of <strong><%= @communities.count %> communities</strong> that are potential matches.<br>
   
    What is most important to you?
  </p>
  <div class="row">
    <div class="col-md-4">
      <%= link_to "Safety", update_lead_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id, priority: "Safety"), method: :post %><br>
      <%= link_to "Care", update_lead_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id, priority: "Care"), method: :post %><br>
      <%= link_to "Location", update_lead_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id, priority: "Location"), method: :post %><br>
      <%= link_to "Budget", update_lead_priorities_journies_path(prospect_id: @prospect.id, lead_id: @lead.id, priority: "Budget"), method: :post %><br>
      <%= form_tag(update_lead_priorities_journies_path) do %>
        <%= text_field_tag :priority, nil, placeholder: 'Enter a priority not listed', class: "form-control" %>
         <%= hidden_field_tag :prospect_id, @prospect.id %>
        <%= hidden_field_tag :lead_id, @lead.id %>
        <div><%= submit_tag 'Next', class: 'btn btn-primary' %></div>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/journies/living.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    Thank you for taking the first step in finding the best care solution for you and your family.  Please take a moment to give us a little better understanding of your individual situation so we can best meet your exact needs.
  </p>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">What is their current living situation? (Multiple answers can be given)</p>
  <div class="row">
    <div class="col-md-6">
      <%= form_tag(update_living_journies_path) do %>
        <%= check_box_tag 'home_alone', 'Living at home alone' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Living at home alone</span><br>
        <%= check_box_tag 'home_with_spouse', 'Living at home with spouse or significant other' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Living at home with spouse or significant other</span><br>
        <%= check_box_tag 'friend', 'Living with a friend' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Living with a friend</span><br>
        <%= check_box_tag 'family', 'Living with family' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Living with family</span><br>
        <%= check_box_tag 'rehab', 'Currently at Rehab' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Currently at Rehab</span><br>
        <%= check_box_tag 'hospital', 'Currently at Hospital' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Currently at Hospital</span><br>
        <%= check_box_tag 'state', 'Living out of state' %><span style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif"> Living out of state</span>
        <%= hidden_field_tag :prospect_id, @prospect.id %>
        <%= hidden_field_tag :lead_id, @lead.id %>
        <div><%= submit_tag 'Next', class: 'btn btn-primary' %></div>
      <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/journies/medical.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif; font-size: 40px">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    What are the current clinical needs?
  </p>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Begin typing the clinical needs in the box and we will display a list of options from which to pick. Add as many as you need.</p>
  <div class="row">
    <div class="col-sm-10">
      <%= form_tag(update_medical_journies_path) do %>
        <%= select_tag :new_license_list_tokens,
                options_from_collection_for_select(TaggingManual.tokens('licenses', params[:q]), 
                    :id, :name), multiple: true, class: "col-md-12", id: 'licenses_list' %>
         <%= hidden_field_tag :prospect_id, @prospect.id %>
        <%= hidden_field_tag :lead_id, @lead.id %>
        <div><%= submit_tag 'Next', class: 'btn btn-primary' %></div>
      <% end %>
    </div>
  </div>
</div>
<br>

<script type="text/javascript">
    $(document).on('turbolinks:load', function() {
      $('#licenses_list').select2({
        theme: "bootstrap"
      });
    });
</script>

app/views/journies/validate_code.html.erb
<br>
<div class="container info-box">
  <h1 style="text-align: center; color: #0075b4;font-family: Source Sans Pro,Arial,Helvetica,sans-serif">Community Search</h1>
  <p style="font-family: Source Sans Pro,Arial,Helvetica,sans-serif">
    There are a total of <strong><%= @communities.count %> communities</strong> that are potential matches.<br>
   
    Please enter the code we sent to your cell phone.
  </p>
  <div class="row">
    <div class="col-md-3">
      <%= form_tag(check_code_journies_path) do %>
        <%= text_field_tag :code, nil, placeholder: 'Enter code', class: "form-control" %>
         <%= hidden_field_tag :prospect_id, @prospect.id %>
        <%= hidden_field_tag :lead_id, @lead.id %>
        <div><%= submit_tag 'Next', class: 'btn btn-primary' %></div>
      <% end %>
    </div>
  </div>
</div>
<br>